### ISSUE TITLE
Can't run the app on build gradle version: 8.3.1

### ISSUE THREAD

**Issue by Mo0Khaled** [ijashuzain/flutter_windowmanager_plus#1]
There is a new update on the gradle version require every plugin/package to [set namespace](https://d.android.com/r/tools/upgrade-assistant/set-namespace) 

exception:
```
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@773999d3 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':flutter_windowmanager_plus'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file.
```
flutter_windowmanager_plus: ^1.0.0
flutter: 3.24.1
kotlin: 1.9.22

Note: I've tried to update this but it seems that the android folder isn't uploaded to GitHub for some reason, appreciate your help if you can upload the folder so I can fix it or fix it from your side.

**Comment by ijashuzain** [comment]
Sure, i will update it as soon as possible, Thank you

**Comment by ijashuzain** [comment]
New version 1.0.1 released
