### ISSUE TITLE
Can't run IOS 18 , Xcode 16

### ISSUE THREAD

**Issue by adham-ashraf77** [ijashuzain/flutter_windowmanager_plus#2]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method addFlags on channel flutter_windowmanager_plus)

error shows when running on iPhone 16.

**Comment by ijashuzain** [comment]
Thanks for reporting, i'll fix this as soon as possible

Please keep in mind that this package is only for android platform.

In the meantime you can wrap addflag function in a condition that checks the platform is android or not.

**Comment by ijashuzain** [comment]
New version 1.0.1 released
